"""Agent instruction prompts"""
from .manager_prompt import MANAGER_PROMPT
from .analyst_prompts import (
    DATA_ANALYST_PROMPT,
    SPEND_ANALYZER_PROMPT,
    EDISCOVERY_SPECIALIST_PROMPT,
    ANOMALY_DETECTOR_PROMPT,
    SPEND_FORECASTER_PROMPT,
    COMPLIANCE_AUDITOR_PROMPT,
)

__all__ = [
    "MANAGER_PROMPT",
    "DATA_ANALYST_PROMPT",
    "SPEND_ANALYZER_PROMPT",
    "EDISCOVERY_SPECIALIST_PROMPT",
    "ANOMALY_DETECTOR_PROMPT",
    "SPEND_FORECASTER_PROMPT",
    "COMPLIANCE_AUDITOR_PROMPT",
]


